### ISSUE TITLE
"4. Execute yt-dlp-gui.exe"

### ISSUE THREAD

**Issue by Plusader** [kannagi0303/yt-dlp-gui#1]
Hi there!

I'd like to test this programm.
I can't find the file "yt-dlp-gui.exe" you mention in your 4th step.
Since the "bin"-folder also has to be placed at its location help is appreciated with this issue.

Best Regards
Daniel

**Comment by kannagi0303** [comment]
thanks!
you can download "yt-dlp-gui.exe" from 
https://github.com/kannagi0303/yt-dlp-gui/releases

and create a subfolder "bin" at  "yt-dlp-gui.exe" location.
download yt-dlp from https://github.com/yt-dlp/yt-dlp/releases
download ffmpeg from https://ffmpeg.org/download.html
then copy yt-dlp.exe and ffmpeg.exe to subfolder "bin"

this is just simple GUI for yt-dlp.
I hope you will like it, if you have any questions, please let me know :)

**Comment by Plusader** [comment]
Thank you!
It works as intended and I like this simple solution very much.

I'd like to see two further features anyway:
1. Automatic analyzing of the copied/pasted URL
2. A limit regarding the quality of the video. I tend to download max 1080p 60fps videos.

If you won't implement them, I put it on my toDo-List (beginning to learn C# in a couple of days ^^).

**Comment by kannagi0303** [comment]
you are welcome

Regarding the two features you propose

Feature 1
This is a function I expect to implement in the future. Since yt-dlp itself supports more than 1.5k websites (URLs), it may not be a good way to continuously execute yt-dlp to determine the available URLs

If yt-dlp itself can be easily judged, I can make this feature in a short time
If there is no way, I will tend to design to judge only a few sites
It is also possible to use the regular matching method to allow the user to set

Feature 2
The current automatic selection is based on the resolution and file size of the video.
The video with the highest resolution is preferred, and the size difference is less than 10%, and h264 will be the main format.
Prioritize sound with high sampling

Originally I expected to provide the ability to set preferences in the GUI in the future.
Thanks for the suggestion, I can design to use the toggle option of "config file" or "GUI settings"
