### ISSUE TITLE
Notification: attach the video's thumbnail

### ISSUE THREAD

**Issue by ShiSheng233** [kannagi0303/yt-dlp-gui#11]
- [ ]  add thumbnail to the notification

_Originally posted by @ShiSheng233 in https://github.com/kannagi0303/yt-dlp-gui/issues/8#issuecomment-1256977497_

**Comment by kannagi0303** [comment]
Adding thumbnails does add to the visual effect
However, in order to achieve this feature, the thumbnails must be downloaded to the local
[reference](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast)

I want to keep the app as portable and clean as possible
Hope to have an idea to better deal with redundant temporary files
