### ISSUE TITLE
aria2 enabled seems not work

### ISSUE THREAD

**Issue by Ber8th** [kannagi0303/yt-dlp-gui#120]
waited for some time and it shows completed but nothing found. The downloading only works when the aria2 is disabled.
Wish I could copy the download addresses manually to use in other downloading tool.

**Comment by kannagi0303** [comment]
Please first confirm whether you have downloaded aria2, which can be referenced at [External-Downloader](https://github.com/kannagi0303/yt-dlp-gui/wiki/External-Downloader), and ensure that aria2 is not blocked by your firewall.

As of now, almost no one has reported this issue, and I cannot determine common problems or the specific issue you are currently facing.

If you wish to use a different downloader, please refer to [yt-dlp #download-options](https://github.com/yt-dlp/yt-dlp#download-options). You can specify it using the ``--downloader` parameter, and you can configure it to use your specified downloader for each download at [Use Configuration](https://github.com/kannagi0303/yt-dlp-gui/wiki/Use-Configuration).

**Comment by Ber8th** [comment]
I confirmed and tested aria2, it's good to normally download but has some error through proxy, maybe that's it.
I checked the --downloader of yt-dlp, ‘Currently supports native, aria2c, avconv, axel, curl, ffmpeg, httpie, wget.’ Well, my favourite downloader is Free Download Manager, and, I'd love to use GUI. May some copy buttons that after the download buttons of the video and audio selection bars works?

**Comment by kannagi0303** [comment]
Thank you for using and responding.

I have tested several proxies I commonly use on my end, and they all work correctly. Since my GUI is quite simple, it doesn't validate the input values but directly applies them to the parameters of yt-dlp. If execution fails, there might be cases where the functionality becomes ineffective or stops, but in most situations, it fulfills my personal requirements.

FDM is a highly mature tool, and I have previously tried various tools like 3dyd, 4k downloader, and others. However, these tools didn't allow me to use them with the most comfortable workflow. That's why I created the yt-dlp-gui project and tried to give it greater flexibility for others to use in their own ways. If you're willing, please share how we can make it more user-friendly for you, or you can also explore other fully mature projects to see if they meet your needs. :)

**Comment by Ber8th** [comment]
I guess it's missing some configuration for aria or something else, but not the GUI.
Maybe I could expect yt-dlp supports FDM in the future. Before that, I can use your GUI to download some short videoes.
Thanx again.
