### ISSUE TITLE
Shortened title

### ISSUE THREAD

**Issue by Plusader** [kannagi0303/yt-dlp-gui#2]
Hi there!

Can you please check why the titles are not completely used for the downloaded file?

I have already set up a shorter path for the destination of the download to check if the previous (longer) one was the cause of the shorter title, but this wasn't the case.

Thank you for your support!

![2022-09-16 12-51-22](https://user-images.githubusercontent.com/35087629/190623799-77b916fd-6121-45fa-85ba-392651959e6c.png)

**Comment by kannagi0303** [comment]
First of all thanks for the testing.

This is a known problem with handling file extensions.
Since most of them are used by individuals and no one has reported them, they have not been dealt with.
Very sorry for the inconvenience

The revised executable file has been released.
Hope you will like this GUI

https://github.com/kannagi0303/yt-dlp-gui/releases/download/2022.09.17/yt-dlp-gui.exe

**Comment by Plusader** [comment]
The dot-issue has been solved. Thanks for the quick fix and the already impressive work!

It could be that it become my favourite downloading-tool quite soon.

Still there are features on which maybe I have to work on myself sooner or later like:
- Automatic analyzing of the copied/pasted URL
- A limit regarding the quality of the video. I tend to download max 1080p 60fps videos. yt-dlp already considers a [config file](https://github.com/yt-dlp/yt-dlp#configuration) for this purpose which could come in handy for such an implementation. I've attached my current one.
- A list of URL's to download them one after another (advanced: simultaneously)

**Comment by kannagi0303** [comment]
Thank you for your positive support

I was also unable to meet my convenience with other tools (GUI), so I started to make this GUI
Now I almost only use my own GUI for downloading :)

Regarding the first two points you mentioned, I have already answered them in the previous issue

As for batch downloads, I have considered that there will be a need for this, but I have not yet thought of maintaining a simple, easy-to-use and reliable design. If you have good ideas, please help me, thank you

**Comment by kannagi0303** [comment]
I have released a [new version](https://github.com/kannagi0303/yt-dlp-gui/releases/tag/2022.09.19).

Right now, You can use [config.txt](https://github.com/kannagi0303/yt-dlp-gui/files/9591713/config.txt) for limit regarding the quality of the video.
Also supported `output template`.

Currently only supported `-f`, `-o`. 
If you are interested, you can test it.

**Comment by Plusader** [comment]
> As for batch downloads, I have considered that there will be a need for this, but I have not yet thought of maintaining a simple, easy-to-use and reliable design. If you have good ideas, please help me, thank you

Hi!

My config.txt isn't considered when analyzing new Videos.
In which folder does the config-file you can select under Options>Configuration has to be placed?

Regarding the batch-download I propose to implement a simple list as a first step.

![2022-10-01 18-13-41 list](https://user-images.githubusercontent.com/35087629/193418785-9e0dd7db-0a10-412e-8ce3-2e67491a8038.png)

Regarding the usage of Aria2 (which is new to me): The downloaded build already comes with quite some attachments which messes up the bin folder (in which yt-dlp.exe and ffmpeg.exe are stored so far). A solution could be to require aria2.exe (including its other files) to be placed in a bin/aria2 folder

Thanks for the work so far!

**Comment by kannagi0303** [comment]
I'm not sure if it's a bug in the program that can't be used.
I have put instructions on how to use the configuration file in the [README](https://github.com/kannagi0303/yt-dlp-gui#readme)
That is, put the configuration file in the subfolder of `configs`
It will be reflected in the drop-down options in `Options` → `Configuration`
This design is convenient to switch to another setting immediately under different conditions.

<hr/>
About batch download

I have found a project with a good interface design [stacher.io](https://stacher.io/)
<img src="https://user-images.githubusercontent.com/78738403/192985314-e2e5fd60-f147-4a55-bc00-0af6f8b9721d.png" width=400/>

I will add your valuable ideas as future improvement directions :)
<hr/>
About attaching files

you are right
Maybe I can have the GUI automatically scan the subfolders, so that the user can place them the way they like
Or add the option of setting to let people customize the path where the attached file is located.

**Comment by Plusader** [comment]
Hi!

I haven't read the readme part regarding the config file (and necessary folder). It works now as intended.

Regarding stacher.io.
I didn't use(know) that software so far. I have used VideoProc, which seems to be similar regarding its video downloads. Both share the Thumbnail in the yet to be downloaded area/section and each line of it, thus making it pretty thick. I suggest to not add it in the list in order to have a more compact/useful URL/Songtitle-listing.

Regarding the attached files.
I think your solution with the config-file is the way to go.
Following this the README could soon be like:

Use Configuration (refer to [configuration](https://github.com/yt-dlp/yt-dlp#configuration))
1. Create a Folder configs in location of executable file
2. Put configuration file(s) into Folder configs (text file)
- Need Restart for scan configuration file(s)

Use Aria2
1. Create a Folder aria2c in location of the yt-dlp.exe
2. Unpack all files from the [latest archive](https://github.com/aria2/aria2/releases) into the newly created folder (containing the aria2c.exe file)

**Comment by kannagi0303** [comment]
I have added the function of automatically scanning attached files, 
Put it in the subfolder, you can organize these files arbitrarily, let executable files keep origin filename, it can be automatically found and used. (even nested folders)
This should work for your needs :)

<hr/>
About batch download interface

In the current version of the thumbnail, you can download the thumbnail separately by right-clicking the mouse. I want to keep this function.

I will try to achieve a compact and practical presentation, possibly through settings to provide different needs.

Anyway, this is the goal for the future.
