### ISSUE TITLE
possible use of configuration file without configs folder

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#22]
currently I am using the yt-dlp, ffmpeg in same folder or location of GUI without any subfolders.

**but the configuration file needs the subfolder to work. I requesting for the possibility of making the config file work same way as other files without the folder.**

**Comment by kannagi0303** [comment]
You just have the opposite needs of another user of mine.
He would like to have more subfolders to categorize related files
Although I have tried to design the GUI to be more flexible

The purpose of placing the configuration files in a separate subfolder is to facilitate users to quickly switch between multiple configuration files when downloading different types of videos

If the GUI can also meet your needs, the way I currently think of
A: When there is no subfolder, only a single configuration file is fixed to read
B: Make a fixed file extension (eg: .cfg) for the config file so that the GUI can correctly understand the config file as those

I will take some time to think about how to implement it, or if there are more people who can give advice
