### ISSUE TITLE
add `log` option

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#25]
possibly to see the yt-dlp process and to find the error issue related to unsuccessful downloads.

**Comment by kannagi0303** [comment]
The `log` function I think is only the most helpful to developers, and I tend not to implement it.
I recommend letting the user know the parameters issued by the GUI, so that it may be easier for ordinary users to understand the problem

For example, you can clearly know that there is a problem with `yt-dlp`, or there is a bug in the `yt-dlp-gui` I made

**Comment by bachig26** [comment]
thanks
