### ISSUE TITLE
`Cancel` Button not working

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#26]
the cancel button doesn't abort the download.

**Comment by kannagi0303** [comment]
Please let me know more details so I can reproduce the problem and fix it

**Comment by bachig26** [comment]
> Please let me know more details so I can reproduce the problem and fix it

https://www.youtube.com/watch?v=XV-sj4s4LqE

So, I was downloading this video and want to cancel them to change the resolution from 1080p to 720p.
I tried clicking the Cancel button but the download doesn’t abort.

**Comment by MWillberg** [comment]
Here the cancel button actually cancels the download process.

But...
- Add url
- Press analyze button
- Press download button
- Download button changes to cancel buitton with an active spinner
- Download is finished, Status is done, thumbnail and video files are usable
- Cancel button has active spinner
- Pressing cacnel button now does nothing, which seems to indicate that there is nothing to cancel

**Comment by kannagi0303** [comment]
Sorry, I'm not sure if the cancel button was accidentally disabled when I added a new feature, I'll check this again, thanks for letting me know

**Comment by kannagi0303** [comment]
I checked my code.
The operation interval between `Download` and `Cancel` is too short, there will be a certain probability of this problem.

Since the program is designed with multi-execution, `Cancel` may occur before `Download` for the program. I will improve it in the next version, and hope to avoid this problem.

Before the next version is released, please pay more attention to users for the time being.

**Comment by kannagi0303** [comment]
The new version `2022-10-10` is released, I have made some changes to prevent users from triggering this bug, I hope this will solve most of the problems

**Comment by kannagi0303** [comment]
thanks for your report

Since I'm not a twitch audience, I can't be sure that the problem occurs when downloading twitch

Regarding the download stream, yt-dlp.exe will execute ffmpeg.exe, not the GUI to execute it,
When I click Cancel, it only sends a termination signal to yt-dlp.exe, and I may not be able to let the GUI manage ffmpeg.exe directly.

Although I can try to delete the ffmpeg process, after all, ffmpeg is a very popular tool and may affect other tools.

So I'll check again to see if there's a better way to make it work without errors. This problem may not be resolved soon, please bear with me

**Comment by kannagi0303** [comment]
Hello

After my test, the problem you described will occur in the environment of Windows 7 SP1.

Since my development environment is Windows 11, I haven't noticed any problems with other versions of the operating system.

I tweaked my code and did a simple test in the Windows 7 SP1 environment, and the problem was solved in the new release, however I didn't spend more time doing more testing, Please let me know if you have any problems in the follow-up use, thank you :)
