### ISSUE TITLE
How about using aria2c as the download backend?

### ISSUE THREAD

**Issue by ShiSheng233** [kannagi0303/yt-dlp-gui#3]
Hi!

It's a feature request though.
I think using aria2c to download video will be faster than using yt-dlp's native downloader.

BTW, how about use this empty area to display the download speed while downloading?
![image](https://user-images.githubusercontent.com/39020034/190863944-e09dc94a-1deb-4877-9253-c3d52ccab472.png)

Appreciate your work~

**Comment by kannagi0303** [comment]
Thanks for your use and suggestion.

I think it's a good idea, yt-dlp also supports using other downloaders
I will test and think how to call the downloader.

As for the section showing download speed information
Since the source is not uniform speed, I can't guarantee accurate numbers,
May take time to adjust to improve accuracy

I suggest to keep this issue open, I will keep updating the information with any progress

感谢您的使用与建议

我认为这是个好主意，yt-dlp也支援使用其他下载器
我会测试与思考如何去调用下载器

至于显示下载速度资讯部分
由于来源并不一定是勻速的，我不敢保证能否提供准确的数字，
可能需要花时间调整来提升准确度

我建议让这issue保持开启，有任何进展我将会持续更新资讯

**Comment by kannagi0303** [comment]
I have released a new version
Can support aria2 downloader, although the download speed cannot be displayed yet
if you are interested, you can test it

我发布了新的版本
可支持aria2c，虽然目前还无法显示下载速度，如果您有兴趣可以测试看看

**Comment by kannagi0303** [comment]
I have released a new version again.
Supported aria2 and display download speed
If you are interested, you can test it :)

**Comment by ShiSheng233** [comment]
Sorry for the delayed reply.

I am studying at school recently, no time for me to get to computer.

I will test it tomorrow, thanks for your contribution.

**Comment by ShiSheng233** [comment]
It worked perfectly!
Appreciate your work very much.

![image](https://user-images.githubusercontent.com/39020034/192098992-010046c1-7441-4c0a-9c47-6f62a80ccca5.png)
