### ISSUE TITLE
Option to preset a Video Format, Audio Format, Subtitle Lang

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#30]
Currently, there is no option to preset an format for video (example: 137) and audio (example: 140) and Subtitle (example: en) as user-defined until there is any further change by user or a reset.

I would like have an option to set this one.

**Comment by kannagi0303** [comment]
The current preset format is the most suitable format for me, and I judge it through a custom formula.

I hope I can better provide a convenient interface to allow users to formulate preset rules. Since the format provided by each video URL is different, it is difficult to design the interface on the GUI.

However, in the current version, you can modify the default format with `config`, use the `-f` parameter, you can add keywords such as bestvideo+bestaudio...etc. (The subtitle part has not been matched yet)

**Comment by bachig26** [comment]
> The current preset format is the most suitable format for me, and I judge it through a custom formula.
> 
> I hope I can better provide a convenient interface to allow users to formulate preset rules. Since the format provided by each video URL is different, it is difficult to design the interface on the GUI.
> 
> However, in the current version, you can modify the default format with `config`, use the `-f` parameter, you can add keywords such as bestvideo+bestaudio...etc. (The subtitle part has not been matched yet)

thanks. 
then, I might close this issue now.
