### ISSUE TITLE
Add support for YTDL-PATCHED

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#36]
[YTDL-PATCHED](https://github.com/ytdl-patched/ytdl-patched)

ytdl-patched is a up-to-date version (snapshot) of yt-dlp and with [few changes/ new features](https://github.com/ytdl-patched/ytdl-patched#new-features-in-ytdl-patched).

**_This issue is to request for adding the ytdl-patched as new backend._**

**Comment by kannagi0303** [comment]
Will try to use ytdl-patched in the future, or you can also try changing the file name to yt-dlp.exe, roughly they share the same parameters (I haven't tried it yet, but in yt-dlp and youtube- dl is common)

**Comment by bachig26** [comment]
> Will try to use ytdl-patched in the future, or you can also try changing the file name to yt-dlp.exe, roughly they share the same parameters (I haven't tried it yet, but in yt-dlp and youtube- dl is common)

Okay I’ll try it.

**Comment by kannagi0303** [comment]
Hello

I adjusted the GUI so that you can automatically map YTDL-PATCHED without changing the file name.

Please pay attention when using, only keep one kind of executable file (yt-dlp or ytdl-pattched or ...) to avoid misuse of GUI.

I didn't take the time to test this project, I made them generic on the premise that they all inherit from youtube-dl.

Hope this fits your needs :)
