### ISSUE TITLE
Stuck on "analyze"

### ISSUE THREAD

**Issue by huhas12** [kannagi0303/yt-dlp-gui#38]
Thank you very nice job!

However after my first download, is stuck on "analyze". Tried to delete and download again and run, but the same issue. Deleted the *.yaml file too, but same result. Any ideas? Could it be network issue, or firewall?

*tried aria too, same problem.

**Comment by kannagi0303** [comment]
Hello

This problem may occur when yt-dlp and ffmpeg are not downloaded to the folder where the executable files are located. You can follow the instructions in the readme.

Since I don't have enough information, there's no way to tell you exactly what's going wrong, you can try different video sites to see if the problem occurs.

If you can provide the URL, or more information (such as the OS version) so that I can reproduce the problem you're having, I'll know more precisely how to fix it.

**Comment by kannagi0303** [comment]
Unable to know the details of the problem for a long time
