### ISSUE TITLE
Chaturbate  Stripchat don't support!

### ISSUE THREAD

**Issue by Ju9aad** [kannagi0303/yt-dlp-gui#40]
https://chaturbate.com/hotangelalli/

**Comment by kannagi0303** [comment]
Hello

The reference URL you provided was not live when I checked it, but I tested the live broadcast of other rooms and it could be recorded normally.

This site is included in the yt-dlp support list.

yt-dlp needs to rely on ffmpeg for streaming recording, so please confirm whether ffmpeg is included.

Or you can also try to use the command line mode to test the operation directly.

Since I don't have any further information, I can't directly solve the problem you mentioned.

**Comment by kannagi0303** [comment]
Long time no further message
