### ISSUE TITLE
Analyse loop

### ISSUE THREAD

**Issue by Rolbag** [kannagi0303/yt-dlp-gui#43]
Build: yt-dlp-gui 2022.11.14
Example adress: https://www.youtube.com/watch?v=Evq3Gqf8F0I
Errror: The analyse load forever. The icon is spinng but not more. 
Antivir: Deactivated, nothing changed.

**Comment by kannagi0303** [comment]
Hello
Since the URL you provided has regional restrictions, I can't help you to confirm further.
It is recommended that you try other videos, or you can enable cookie testing (the website may require you to log in)
As for antivirus software, it shouldn't have any effect, and the way of reading information is not much different from that of browsers. In theory, as long as your browser can access the URLs, there should be no problem.

Notes:
Since it's just a GUI, don't forget to configure yt-dlp.exe, I put the detailed instructions on the wiki page

**Comment by Rolbag** [comment]
The videolink above was an example, I tested some more for sure. :)
Next example: https://www.youtube.com/watch?v=Ye_6d9N55IM
Also same strange bug/feature. The icon spins forever but nothing more.
