### ISSUE TITLE
location for config file

### ISSUE THREAD

**Issue by trzustka** [kannagi0303/yt-dlp-gui#46]
create config file (yaml) in '%appdata%\yt-dlp-gui' folder
as not always every user has needed permissions to write in every folder

**Comment by kannagi0303** [comment]
I'm sorry
I don't quite understand your question (or need)
If it is convenient, please explain the details concisely, thank you

**Comment by trzustka** [comment]
if executable is in location that user have read (and execute) permissions but not write/modify program will not run (not even show any error message) (it could be be another issue...)

it is better to check several places if user has write/modify permissions there to place config file for yt-dlp-giu

one of this kind of places is %appdata% (C:\Users\<user>\AppData\Roaming\) where every user has its own location for its own program settings

please add this functionality:
if folder where .exe is run from does not allow user to save files, save .yaml config file to %appdata%\yt-dlp-gui

**Comment by kannagi0303** [comment]
Thank you for your reply and explanation. I understand.

Because my default is only for personal use, and there is no support in the permission part.

As you suggested, I will add permission warning message first in future version, and find better way to solve storage (temporary) file(s).

I would like to be able to remove the GUI completely and simply and cleanly when users feel it is not suitable. So I tried without AppData or even Temp folder.

If you have a good idea, please let me know, thank you.

**Comment by kannagi0303** [comment]
Hello, sorry for keeping you waiting! 

Currently, even without permission, the GUI can be started normally, and it can be used except for the inability to save. 

However, I did not test each step in detail. If you are interested, you can try the new version.
