### ISSUE TITLE
Need to copy yt-dlp and ffmpeg; why not using PATH environment variable?

### ISSUE THREAD

**Issue by fds39** [kannagi0303/yt-dlp-gui#54]
yt-dlp and ffmpeg are already installed on my system with the path environment variables correctly set. Would it be possible to take this into account and not have to install the 2 exe in the same folder?
Of course it is not very complicated to follow your procedure but I use the Chocolatey package system to easily update (in 1 or 2 clicks) all the packages.
By the way, I'm considering opening a Chocolatey package request for your excellent yt-dlp_GUI https://github.com/chocolatey-community/chocolatey-package-requests
Then everything would be perfectly integrated, a perfect solution for my teacher wife at school...

But perhaps you have an objection, or even a reluctance?

**Comment by ChristopherTheBoss** [comment]
I <3 UR GUI @kannagi0303 

This is a reasonable suggestion. I tried it from my path too before copying the executables.

**Comment by kannagi0303** [comment]
First of all, thank you for using

Sorry for not being able to configure it the way you like.
Because I have been unable to find a suitable tool for myself for a long time, I made this GUI with my own habits and preferences.

I can understand the feeling of not being able to find a suitable tool, and I will try my best to add the required functions when possible.

I can add a few setting items so that the dependent executable files can be placed in other folders, which is relatively simple

I only have a simple understanding of `chocolatey`. I don't have the ability to make its package at present. This GUI is made by me on vacation or in my spare time. It is just an amateur (hobby) project.

If you are willing to provide a convenient method for this project, I am very welcome, and I can learn from it.

In the case that the operation logic has not changed too much, anyone is welcome to make suggestions or discuss and communicate with us what can be improved

**Comment by fds39** [comment]
I can't help you with the creation of a Chocolatey package. In fact, it's a matter of submitting a request for a maintainer to decide to take on this task.
Of course if the author himself takes care of it, it's even simpler and faster to implement. Not knowing anything about it, I can't assure you of the simplicity of the procedure.
https://docs.chocolatey.org/en-us/create/create-packages
What I know is that before starting anything, the maintenance manager contacts the author to make sure that he has the necessary rights linked to the copyright.

Anyway, I will probably wait for your next improvements to submit a request. I also wanted to congratulate you for sharing the pleasant experience of your lightweight software.

**Comment by kannagi0303** [comment]
I'm sorry for keeping you waiting!

I have released a new version. Although it is not yet possible to set different paths in the UI, you can manually add path settings in the yaml file. There are three items available:

* PathYTDLP
* PathAria2
* PathFFMPEG

You can try running it first and then modifying the contents. 
However, I have not extensively tested it, so I hope you won't encounter any issues when using it.
 If you are interested, you can try the new version. Thank you.

**Comment by fds39** [comment]
Thanks, that's Great now! By the way, this is the french language:

[yt-dlp-gui.txt](https://github.com/kannagi0303/yt-dlp-gui/files/10893048/yt-dlp-gui.txt)

**Comment by kannagi0303** [comment]
Merci à vous !

I hope this GUI can truly help you, and thank you for providing the French translation.
I have already added the French translation.
