### ISSUE TITLE
The text font size is too small

### ISSUE THREAD

**Issue by ElektroStudios** [kannagi0303/yt-dlp-gui#60]
This is very difficult to read for many adult people, specially the text inside the drop-down lists:

![](https://i.imgur.com/p3jIHox.png)

It is an atypical and excessively tiny font size.

Can you consider to increase the default text font size (for all the controls in the UI), or better if you can consider to add a setting to let the end-user choose their desired text font size.

Thanks for your work.

------------------

**EDIT:** The main screenshot that you uploaded into the README.MD has a more readable text / a font size that it seems 1 or 2 points bigger compared to my screenshot. Not sure why. I'm on Windows 10, and I didn't personalized DPI, system font or anything strange that can affect to it. Normally I see normal / bigger font sizes in all kind of programs compared to the font size used in your program.

**Comment by kannagi0303** [comment]
Thank you for your use and suggestions.
First of all, I am very sorry for the inconvenience caused to you.

Your suggestion is very reasonable. I will try to release all controllable settings to users to make decisions, but I am not sure when this function will be implemented.

This project is mainly for me personally, because I can't find free software for myself on the Internet.

In my development environment, I have a 50-inch screen and use it very close, so I have reduced the font size compared to other software

(Because this project is just a hobby, and currently only I am maintaining it, there is no timetable for when it will be implemented, please understand, thank you)

**Comment by ElektroStudios** [comment]
No worries, and of course take your time, without rushing. What is important to me is that you have considered and accepted my proposal for the next release. Thank you.
