### ISSUE TITLE
[Bug] TargetPath and TargetPath Button

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#68]
1. with the [new version](https://github.com/kannagi0303/yt-dlp-gui/releases/tag/2023.03.05), I can't change the Download TargetPath. Even if I change it using the config file, it resets to default when opening yt-dlp-gui as a new session.

2. also the button to open the target path location doesn't work.

**Comment by kannagi0303** [comment]
Thank you for testing. 
I have tried several times myself, but I couldn't reproduce the issue you encountered. 

Regarding the configuration file, when there are changes to each entity, it will save its own state as a configuration file. 
You can try operating under a single execution state to see if the same issue occurs. 
If there are still problems, please let me know your operating sequence and steps so that I can reproduce this issue. 

Thank you

**Comment by bachig26** [comment]
> Thank you for testing. I have tried several times myself, but I couldn't reproduce the issue you encountered.
> 
> Regarding the configuration file, when there are changes to each entity, it will save its own state as a configuration file. You can try operating under a single execution state to see if the same issue occurs. If there are still problems, please let me know your operating sequence and steps so that I can reproduce this issue.
> 
> Thank you

I tried again, and it's works fine now. 
I'll close this issue for now. thanks.
