### ISSUE TITLE
[Enhancement] UI Scale: change to dial or counter type

### ISSUE THREAD

**Issue by bachig26** [kannagi0303/yt-dlp-gui#74]
the new scale size slider option needs to be in fullscreen because when the gui is in windowed mode, when going beyond 100%+ the slider gets hidden and can't able get it normal unless it's in fullscreen.

**this issue is to implement the scale option with the dial or counter type instead of the current slider type.**

**Comment by kannagi0303** [comment]
Thank you for your quick response and continued attention to my GUI. 

I'm not sure what difficulties may arise from adding more small widgets, and I can't predict how it will look on every user's screen. I would like to leave this issue open for a while and see if other users have any feedback.

I'm not sure I understand what you mean by ```dial``` or ```counter```. If you have a background in programming, perhaps you could use control names such as ```ComboBox``` or ```NumericUpDown```, which would help me better understand the type of control you are referring to. Alternatively, if it's not too much trouble, you could provide a picture.

Perhaps I could add some ```emergency measures```, such as a ```shortcut key``` to quickly restore the position and size. If anyone else has ideas, please feel free to suggest them. :)

**Comment by bachig26** [comment]
> I'm not sure I understand what you mean by `dial` or `counter`. If you have a background in programming, perhaps you could use control names such as `ComboBox` or `NumericUpDown`, which would help me better understand the type of control you are referring to. Alternatively, if it's not too much trouble, you could provide a picture.

yes, I was refering to `ComboBox` or `NumericUpDown` control box. sorry, i left learning programming for years and i have forgot many things. I prefer having `NumericUpDown` control for scale if possible.

> Perhaps I could add some `emergency measures`, such as a `shortcut key` to quickly restore the position and size.

that's a good function to have like an `restore defaults` option.

also, i just thought it would be nice to have a config file backup option incase of accidental restoring to defaults where the user can replace the backup config file.

**Comment by kannagi0303** [comment]
Hello,

I have replaced the SliderBar with a simple Textbox that allows users to directly input values and change the numeric value by using the up and down arrow keys or mouse scroll wheel. 

Due to significant changes in the new version, there may be some rough edges. If you're interested, you can try it out and see how it works.

**Comment by bachig26** [comment]
> I have replaced the SliderBar with a simple Textbox that allows users to directly input values and change the numeric value by using the up and down arrow keys or mouse scroll wheel.

I like the text box, it actually well, even when set at 10% or 200% I can still able to resize back to different values as it's visible and the input cursor is still in the scale option. 👍❤

> Due to significant changes in the new version, there may be some rough edges. If you're interested, you can try it out and see how it works.

yes, I can see the rough edges, and also I want mention that i can see a white line/edge in the right end (outside) of the yt-dlp-gui window. i hope it's fixed in next/upcoming releases.

**Comment by kannagi0303** [comment]
Thank you for your prompt response.

Perhaps the translation tool caused some variation in my wording, and I was surprised that you saw a white line. In my environment, there is no such phenomenon, so if possible, could you please provide me with a screenshot so that I can see the issue?

My intention was to say that the new version may not work perfectly as expected.

**Comment by bachig26** [comment]
> Thank you for your prompt response.

✌

> My intention was to say that the new version may not work perfectly as expected.

👍

> Perhaps the translation tool caused some variation in my wording, and I was surprised that you saw a white line. In my environment, there is no such phenomenon, so if possible, could you please provide me with a screenshot so that I can see the issue?

i can only see this white line issue in this new version [[2023.03.20](https://github.com/kannagi0303/yt-dlp-gui/releases/tag/2023.03.20)], you can see the clip below:


https://user-images.githubusercontent.com/96393348/226270435-afc3f1be-f01b-475c-b8f6-2ef776704619.mp4

**Comment by kannagi0303** [comment]
Thank you, I believe this may be caused by the version of Windows. I tested it on Windows 7 and encountered the same issue (even worse), but I did not experience this problem when using Windows 11.

A major reason for this might be that I moved the Tab control to the outer layer, causing discrepancies in calculations for different versions of Windows. I think that adjusting the position of the UI and control should be able to fix this issue.

**Comment by kannagi0303** [comment]
Hello.

I re-uploaded the file and it solved the problem on my Window7.
Just a small change, I didn't change the version number.

The reason is not the part I predicted, obviously I made a stupid mistake, I used a wrong parameter.

However, this error has existed since the implementation of the scale feature (including the previous version), it was just not found.

I hope this fix works in your environment as well.
Thanks again for your assistance.
